version: "3.8"
services:
  goshop:
    image: github.com/ahmed-eid-faried/ecommerce-backend-golang
    build: .
    ports:
      - "8888:8888"
    environment:
      PORT: 8888
      AUTH_SECRET: auth_secret
      DATABASE_URI: postgres://myuser:password@mypostgres:5432/mydatabase
      REDIS_URI: redis:6379
      REDIS_DB: 0
    depends_on:
      - mypostgres
      - redis

  redis:
    image: "redis:alpine"

  mypostgres:
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
# version: "3.8"
# services:
#   goshop:
#     image: github.com/ahmed-eid-faried/ecommerce-backend-golang
#     build: .
#     ports:
#       - "8888:8888"
#     environment:
#       port: 8888
#       auth_secret: auth_secret
#       database_uri: postgres://postgres:1234@postgres:5432/postgres
#       redis_uri: redis:6379
#       redis_db: 0

#     depends_on:
#       - postgres
#       - redis

#   redis:
#     image: "redis:alpine"

#   postgres:
#     restart: always
#     image: "postgres:latest"
#     environment:
#       DATABASE_USER: postgres
#       POSTGRES_PASSWORD: 1234
