version: "3.8"
services:
  goshop:
    image: "github.com/quangdangfit/goshop"
    build: .
    ports:
      - "8888:8888"
    environment:
      port: 8888
      auth_secret: auth_secret
      database_uri: postgres://postgres:1234@postgres:5432/postgres
      redis_uri: redis:6379
      redis_db: 0

    depends_on:
      - postgres
      - redis
    volumes:
      - shop-data:/app/data

  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data

  postgres:
    restart: always
    image: "postgres:latest"
    environment:
      DATABASE_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  shop-data:
  redis-data:
  postgres-data:
