version: "3.8"
services:
  goshop:
    image: github.com/ahmed-eid-faried/ecommerce-backend-golang
    build: .
    ports:
      - "8888:8888"
    environment:
      port: 8888
      auth_secret: auth_secret
      database_uri: postgres://postgres:1234@postgres:5432/postgres
      redis_uri: redis:6379
      redis_db: 0
    depends_on:
      - postgres
      - redis

  redis:
    image: "redis:alpine"

  postgres:
    restart: always
    image: "postgres:latest"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
# version: "3.8"
# services:
#   goshop:
#     image: github.com/ahmed-eid-faried/ecommerce-backend-golang
#     build: .
#     ports:
#       - "8888:8888"
#     environment:
#       port: 8888
#       auth_secret: auth_secret
#       database_uri: postgres://postgres:1234@postgres:5432/postgres
#       redis_uri: redis:6379
#       redis_db: 0

#     depends_on:
#       - postgres
#       - redis

#   redis:
#     image: "redis:alpine"

#   postgres:
#     restart: always
#     image: "postgres:latest"
#     environment:
#       DATABASE_USER: postgres
#       POSTGRES_PASSWORD: 1234
